version: 2
updates:
  # Mantieni aggiornato il Backend (NuGet)
  - package-ecosystem: "nuget"
    directory: "/src/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # Mantieni aggiornato il Frontend (NPM)
  - package-ecosystem: "npm"
    directory: "/src/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

  # Mantieni aggiornate le GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
