services:
  goleador-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: goleador_sql_server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong!Passw0rd # Password complessa obbligatoria
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

volumes:
  mssql-data: