services:
  # Database
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: goleador_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    volumes:
      - mssql-prod-data:/var/opt/mssql
    restart: always

  # Backend API
  api:
    image: ghcr.io/nofiss/goleador/goleador-api:latest
    container_name: goleador_api
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=GoleadorDb;User Id=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=True;
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=GoleadorApi
      - Jwt__Audience=GoleadorClient
    ports:
      - "8080:8080" # L'API risponde sulla 8080
    depends_on:
      - db
    restart: always

  # Frontend React
  web:
    image: ghcr.io/nofiss/goleador/goleador-web:latest
    container_name: goleador_web
    ports:
      - "80:80" # Il sito risponde sulla 80 standard
    depends_on:
      - api
    restart: always

  goleador_seq:
    image: datalust/seq:latest
    container_name: goleador_seq
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
    restart: always

volumes:
  mssql-prod-data:
