name: ðŸ³ Docker Publish

on:
  push:
    branches: ["main"]
    # Esegui solo se cambiano file rilevanti
    paths:
      - "src/backend/**"
      - "src/frontend/**"
      - ".github/workflows/docker-build.yml"

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # FONDAMENTALE: permette di caricare l'immagine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Downcase REPO name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
        env:
          GITHUB_REPOSITORY: "${{ github.repository }}"

      # 1. Login su GitHub Container Registry
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 2. Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3. Build & Push BACKEND
      - name: Build and push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./src/backend
          file: ./src/backend/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/goleador-api:latest

      # 4. Build & Push FRONTEND
      - name: Build and push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./src/frontend
          file: ./src/frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}/goleador-web:latest
